ALTER TABLE "Product"
ADD COLUMN "salePrice" DOUBLE PRECISION,
ADD COLUMN "description" TEXT NOT NULL DEFAULT '',
ADD COLUMN "sku" TEXT,
ADD COLUMN "stockQuantity" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "weight" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "height" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "width" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "length" DOUBLE PRECISION NOT NULL DEFAULT 0;

UPDATE "Product"
SET "sku" = CONCAT('SKU-', "id")
WHERE "sku" IS NULL OR "sku" = '';

ALTER TABLE "Product"
ALTER COLUMN "sku" SET NOT NULL;

CREATE UNIQUE INDEX "Product_sku_key" ON "Product"("sku");
