import { Product } from '../types/product';

export const seedProducts: Product[] = [
  {
    id: '1',
    name: 'CROPPED JULY',
    price: 59.99,
    image: '/assets/product-1.png',
    category: 'Cropped',
    tag: 'lancamento',
    installments: { count: 2, value: 30.0 },
  },
  {
    id: '2',
    name: 'VESTIDO FLORA',
    price: 79.99,
    image: '/assets/product-2.png',
    category: 'Vestido',
    tag: 'lancamento',
    installments: { count: 2, value: 40.0 },
  },
  {
    id: '3',
    name: 'SHORT LARA',
    price: 89.99,
    image: '/assets/product-3.png',
    category: 'Short',
    tag: 'lancamento',
    installments: { count: 2, value: 45.0 },
  },
  {
    id: '4',
    name: 'BLUSA CARMEN',
    price: 49.99,
    image: '/assets/product-4.png',
    category: 'Blusa',
    tag: 'lancamento',
  },
  {
    id: '5',
    name: 'SAIA LOLLA',
    price: 89.99,
    image: '/assets/product-5.png',
    category: 'Saia',
    tag: 'destaque',
    installments: { count: 2, value: 45.0 },
  },
  {
    id: '6',
    name: 'BODY TROPICAL',
    price: 39.99,
    originalPrice: 49.99,
    image: '/assets/product-6.png',
    category: 'Body',
    tag: 'oferta',
  },
  {
    id: '7',
    name: 'MACAQUINHO EVA',
    price: 69.99,
    image: '/assets/product-7.png',
    category: 'Macaquinho',
    tag: 'destaque',
    installments: { count: 2, value: 35.0 },
  },
];
